---
title: "Parliament"
author: "Fousseynou Bah"
date: "May 31, 2018"
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
load(file = "parliament.RData")

##########################################################################
########################################/// PACKAGES ///
##########################################################################
library("tidyverse")
library("plotly")
#Setting the theme for ggplot
theme_set(theme_bw())

```


# A glimpse of the balance of power


```{r district_balance, echo=FALSE, fig.align='center',fig.show='animate', message=FALSE, warning=FALSE,out.width="90%"}

districts <- mp_df %>% filter(!is.na(firstname)) %>% group_by(district) %>% summarise(number = n())
shares_mp_list <- list()

for(i in districts$district){
  
  shares_mp_list[[i]] <- 
    mp_df %>% 
    filter(!is.na(firstname)) %>% 
    group_by(party, district) %>% 
    summarise(elected = n()) %>%
    mutate(one = 1) %>% 
    filter(district == i) %>% # filter(district == districts[i, "district"]) 
    ggplot() +
    geom_col(aes(x = district, y = elected, fill = party), width = 1) +
    coord_polar(theta = "y") +
    theme(legend.position = "bottom") +
    theme(axis.line = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank()) +
#    theme(panel.background = element_rect(fill = "white")) +
    scale_fill_brewer(type = "seq", palette = "Set2") +
    labs(x = "", y = "", fill = "Party",
       title = paste(i),
       subtitle = paste("Legislature 2014-2018:", districts[districts$district==i, "number"], "seat(s)"),
       caption = "Source: Data from http://assemblee-nationale.ml/liste-des-deputes/")
  
  print(shares_mp_list[[i]])

}


```



# An overview with mapping

```{r parliament_map_gen, echo=FALSE, fig.align='center',fig.show='animate', message=FALSE, warning=FALSE,out.width="90%"}

##########################################################################
### A particular shapefile: mixing districts and counties (communes)

map_districts <- bind_rows(
  map_cercles %>% 
    filter(!(Admin1_Nam == "Bamako")) %>% 
    mutate(source = "cercles"),
  map_communes %>% 
    filter(Admin2_Nam == "Bamako") %>% 
    mutate(source = "communes")
  ) %>% 
  mutate(shapefile = case_when(source == "cercles" ~ as.character(Admin2_Nam),
                               source == "communes" ~ as.character(Admin3_Nam)),
         shapefile = str_trim(shapefile))


##########################################################################
### A wide data frame of elected officials per district per party

elected_districts <- 
  mp_df %>% 
  filter(!is.na(firstname)) %>% 
  group_by(district, party) %>% 
  summarise(count = n()) %>%
  spread(key = party, value = count) %>% 
  mutate(parliament = district) %>% 
  left_join(join_districts,
            by = c("parliament")) %>% 
  gather(key = party, value = count, -c(district, parliament, shapefile)) %>%
  group_by(parliament, shapefile, party) %>% 
  summarise(count = sum(count, na.rm = TRUE)) %>% 
  mutate(elected = ifelse(count > 0, 1, 0),
         elected = factor(elected, 
                          levels = c(1,0),
                          labels = c("Elected", "Not elected"),
                          ordered = TRUE)) 

##########################################################################
### Mapping with ggplot2
parties <- 
  elected_districts %>% 
  group_by(party) %>% 
  summarise(districts = sum(elected == "Elected", na.rm = TRUE),
            seats = sum(count, na.rm = TRUE))

parties_map_list <- list()

for(i in parties$party){
  parties_map_list[[i]] <- 
    map_districts %>% 
    left_join(
      elected_districts %>% filter(party == i),
      by = c("shapefile")) %>% 
    ggplot() +
    geom_polygon(aes(x = long, y = lat, group = group, fill = elected)) +
    geom_path(aes(x = long, y = lat, group = group), colour = "white", size = 0.025) +
    coord_map() +
    theme(legend.position = "bottom") +
    theme(axis.line = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank()) +
    theme(strip.background = element_rect(fill = "transparent")) +
    theme(panel.grid = element_blank(),
          panel.border = element_blank()) +
    scale_fill_manual(values = c("darkorange", "grey80")) +
    labs(x = "", y = "", fill = "",
       title = paste(i),
       subtitle = paste("Legislature 2014-2018:", 
                        parties$districts[parties$party == i], "district(s) and",
                        parties$seats[parties$party == i], "seat(s)"),
       caption = "Source: Data from http://assemblee-nationale.ml/liste-des-deputes/")
  
  print(parties_map_list[[i]])
# parties_map_list[[i]] <- ggplotly(parties_map_list[[i]])
  
}

```

